import assert from 'node:assert/strict';
import host from '../dist/server/index.js';
let forwarded;
globalThis.fetch=async(url,opts)=>{forwarded={url,opts};return new Response('{"username":"Test"}',{headers:{'Set-Cookie':'__Host-eego_session=test; Path=/; HttpOnly; Secure; SameSite=Strict'}});};
const req=(headers={},body='{}')=>new Request('https://eego.example/api/eego',{method:'POST',headers:{'content-type':'application/json','x-eego':'1',...headers},body});
assert.equal((await host.fetch(new Request('https://eego.example/'))).status,200);
assert.equal((await host.fetch(new Request('https://eego.example/not-a-file'))).status,404);
assert.equal((await host.fetch(req({origin:'https://attacker.example'}))).status,403);
assert.equal((await host.fetch(req({'sec-fetch-site':'cross-site'}))).status,403);
assert.equal((await host.fetch(req({'content-type':'text/plain'}))).status,415);
assert.equal((await host.fetch(req({},'x'.repeat(100000)))).status,413);
const response=await host.fetch(req({origin:'https://eego.example',cookie:'hosting_session=private; __Host-eego_session=abc; unrelated=secret','x-forwarded-for':'spoofed','cf-connecting-ip':'192.0.2.1',authorization:'Bearer hidden'}));
assert.equal(response.status,200);
assert.equal(forwarded.opts.headers.Cookie,'__Host-eego_session=abc');
assert.equal(forwarded.opts.headers['X-Real-IP'],'192.0.2.1');
assert.equal(forwarded.opts.headers.authorization,undefined);
assert.equal(forwarded.opts.redirect,'manual');
assert.match(response.headers.get('set-cookie'),/HttpOnly; Secure/);
assert.match(response.headers.get('content-security-policy'),/connect-src 'self'/);
console.log('PASS: host routing, bounded bodies, CSRF rejection, cookie isolation and upstream session response.');
globalThis.fetch=async()=>new Response(null,{status:302,headers:{Location:'https://untrusted.example/','Set-Cookie':'__Host-eego_session=untrusted; Secure; Path=/'}});
const redirected=await host.fetch(req());
assert.equal(redirected.status,502);
assert.equal(redirected.headers.get('location'),null);
assert.equal(redirected.headers.get('set-cookie'),null);
console.log('PASS: upstream redirects rejected without forwarding location or cookies.');
