import assert from 'node:assert/strict';
let handler;
const dbToken='b'.repeat(64), session='a'.repeat(64);
globalThis.Deno={env:{get:k=>k==='SUPABASE_URL'?'https://db.test':'test-service-key'},serve:f=>{handler=f;}};
let rpcResult={status:200,data:{ok:true}}, lastRpc;
globalThis.fetch=async(url,opts)=>{assert.equal(url,'https://db.test/rest/v1/rpc/eego_api');lastRpc=JSON.parse(opts.body);return new Response(JSON.stringify(rpcResult),{status:200,headers:{'content-type':'application/json'}});};
await import('../backend/index.ts');
const call=(action,data={},headers={},raw=null)=>handler(new Request('https://site.test/api/eego',{method:'POST',headers:{'Content-Type':'application/json','X-Eego':'1',...headers},body:raw??JSON.stringify({action,data})}));
let n=0;
async function check(name,fn){await fn();n++;console.log('PASS',name);}
await check('anonymous user rejected',async()=>assert.equal((await call('me')).status,401));
await check('unknown action rejected',async()=>assert.equal((await call('admin_wipe')).status,400));
await check('missing CSRF header rejected',async()=>assert.equal((await call('login',{}, {'X-Eego':''})).status,403));
await check('cross-site write rejected',async()=>assert.equal((await call('login',{}, {'Sec-Fetch-Site':'cross-site'})).status,403));
await check('OPTIONS does not enable CORS',async()=>assert.equal((await handler(new Request('https://site.test/api/eego',{method:'OPTIONS'}))).status,405));
await check('non-JSON rejected',async()=>assert.equal((await call('login',{}, {'Content-Type':'text/plain'})).status,415));
await check('malformed JSON rejected',async()=>assert.equal((await call('login',{}, {},'{')).status,400));
await check('oversized payload rejected',async()=>assert.equal((await call('login',{}, {},'x'.repeat(100000))).status,413));
await check('login cookie is secure and token not in body',async()=>{rpcResult={status:200,token:session,data:{username:'Test'}};const r=await call('login',{username:'Test',password:'fixture'});assert.equal(r.status,200);assert.match(r.headers.get('set-cookie'),/HttpOnly; Secure; SameSite=Strict/);assert.equal(r.headers.get('cache-control'),'no-store, private');assert.deepEqual(await r.json(),{username:'Test'});});
await check('user session forwarded only via cookie',async()=>{rpcResult={status:200,data:{username:'Test'}};await call('me',{}, {'Cookie':'__Host-eego_session='+session});assert.equal(lastRpc.p_token,session);assert.equal(lastRpc.p_action,'me');});
await check('worker uses a separate bearer token',async()=>{await call('worker_claim',{}, {'Authorization':'Bearer '+dbToken});assert.equal(lastRpc.p_token,dbToken);});
await check('bearer worker token cannot act as browser session',async()=>assert.equal((await call('me',{}, {'Authorization':'Bearer '+dbToken})).status,401));
await check('logout revokes browser cookie',async()=>{rpcResult={status:200,data:{ok:true}};const r=await call('logout',{}, {'Cookie':'__Host-eego_session='+session});assert.match(r.headers.get('set-cookie'),/Max-Age=0/);});
await check('throttling has retry-after',async()=>{rpcResult={status:429,error:'Try later'};const r=await call('login');assert.equal(r.status,429);assert.equal(r.headers.get('retry-after'),'900');});
await check('health endpoint is public',async()=>{rpcResult={status:200,data:{app:'Eego',database:true}};const r=await handler(new Request('https://site.test/health'));assert.equal(r.status,200);assert.equal(lastRpc.p_action,'health');});
console.log(`${n} mocked Edge HTTP tests passed. No real Edge endpoint was contacted.`);
