'use strict';
const $ = (id) => document.getElementById(id);
const esc = (x) => String(x ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state = { user:null, stats:{}, view:'home', kind:'all', level:'all', search:'', offset:0, historyOffset:0, mistakes:false, active:null, generation:{kind:'vocabulary',level:'B1',count:10,topic:'mixed',weakOnly:false}, version:0 };
let polling, searchTimer, toastTimer, itemRequest=0, historyRequest=0, startingPractice=false;
const formatDate = (date) => date ? new Intl.DateTimeFormat('en-GB',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',timeZone:'Asia/Tokyo'}).format(new Date(date)) : 'Not studied yet';
const levels = (all=true, selected='all') => `${all?'<option value="all">All levels</option>':''}${['B1','B2','C1','C2'].map(x=>`<option ${x===selected?'selected':''}>${x}</option>`).join('')}`;
const categories = (all=true,selected='all') => `${all?'<option value="all">All categories</option>':''}<option value="vocabulary" ${selected==='vocabulary'?'selected':''}>Vocabulary</option><option value="grammar" ${selected==='grammar'?'selected':''}>Grammar</option>`;
const empty = (title,text,action='learn',button='Browse lessons') => `<div class="empty"><div class="symbol">✳</div><h2>${esc(title)}</h2><p>${esc(text)}</p>${button?`<button class="btn secondary" data-nav="${esc(action)}">${esc(button)}</button>`:''}</div>`;
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),6000);}
async function api(action,data={}){
  let r;
  try{r=await fetch('/api/eego',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-Eego':'1'},body:JSON.stringify({action,data}),signal:AbortSignal.timeout(25000)});}catch{throw new Error('Cannot reach the server. Check your connection and try again.');}
  let result;try{result=await r.json();}catch{throw new Error('The backend is not available. Your saved answers have not been changed.');}
  if(!r.ok){const error=new Error(result.error||'The request failed. Please try again.');error.status=r.status;throw error;}
  return result;
}
function saveActive(){try{if(state.active) sessionStorage.setItem('eego_active_v1',JSON.stringify({username:state.user,...state.active}));else sessionStorage.removeItem('eego_active_v1');}catch{/* Storage restrictions do not prevent server-side saving. */}}
function restoreActive(){try{const a=JSON.parse(sessionStorage.getItem('eego_active_v1')||'null');if(a?.username===state.user&&Array.isArray(a.questions)&&a.index<a.questions.length)state.active=a;}catch{try{sessionStorage.removeItem('eego_active_v1');}catch{}}}
function login(message=''){
 clearInterval(polling);state.user=null;state.version++;
 $('app').innerHTML=`<main class="login-wrap"><section class="login-story"><div class="wordmark">eego<span>✳</span></div><div class="eyebrow">Your English, a little further</div><h1>Find the words.<br>Make them yours.</h1><p class="intro">Vocabulary in context. Grammar that clicks. A quiet space to build the English you want to use.</p><div class="sample-cards" aria-hidden="true"><div class="sample-card"><small>A word, many possibilities</small><b>compelling</b><p>心を引きつける・説得力のある</p></div><div class="sample-card front"><small>Learn · recall · use</small><b>In your own words.</b><p>A little practice. A little progress.</p></div></div></section><section class="login-box"><div class="eyebrow">Private learning space</div><h2>Welcome back.</h2><p class="small muted">Sign in to continue where you left off.</p><form id="login-form" class="stack"><label class="field">Username<input name="username" autocomplete="username" required maxlength="80" placeholder="Your username" autocapitalize="none" spellcheck="false"></label><label class="field">Password<div class="pass-wrap"><input id="login-password" type="password" name="password" autocomplete="current-password" required maxlength="128" placeholder="Your password"><button type="button" data-action="toggle-password" aria-label="Show password">Show</button></div></label><div id="login-error" class="error ${message?'':'hidden'}" role="alert">${esc(message)}</div><button class="btn" type="submit">Step inside </button></form><p class="foot">Invitation only. No public sign-up.</p></section></main>`;
}
function shell(){
 const nav=[['home','⌂','Home'],['learn','Aa','Learn'],['weak','◎','Weak items'],['history','◷','History'],['generate','✳','Generate']];
 const s=state.stats;
 $('app').innerHTML=`<div class="shell"><aside class="sidebar"><div class="wordmark">eego<span>✳</span></div><nav aria-label="Main navigation">${nav.map(([id,icon,label])=>`<button class="nav-btn ${state.view===id?'active':''}" data-nav="${id}" ${state.view===id?'aria-current="page"':''}><span class="nav-icon" aria-hidden="true">${icon}</span><span>${label}</span></button>`).join('')}</nav><div class="sidebar-bottom"><div class="user-chip"><div class="avatar">${esc(state.user?.slice(0,1)||'M')}</div><div><b class="small">${esc(state.user)}</b><div class="small muted">Your own pace</div></div></div><button class="text-button" data-nav="settings">Settings & export</button></div></aside><main class="main"><header class="topline"><div class="small">YOUR PERSONAL ENGLISH NOTEBOOK</div><div class="wordmark mobile-brand">eego<span>✳</span></div><div class="row"><span id="connection-status" class="status ${s.workerOnline?'online':''}">${s.workerOnline?'Codex connected':'Codex not connected'}</span><button class="text-button" data-nav="settings" aria-label="Open settings">Settings</button></div></header><div id="content"><div class="loading">Opening your notebook…</div></div></main></div>`;
}
async function navigate(view){
 clearInterval(polling);state.view=view;const version=++state.version;shell();window.scrollTo({top:0});
 try{
   state.stats=await api('dashboard');if(version!==state.version)return;
   updateStatus();
   if(view==='home')home();else if(view==='learn'||view==='weak'){catalogFrame(view);await loadItems(version);}else if(view==='history'){historyFrame();await loadHistory(version);}else if(view==='generate'){generator();await loadJobs(version);polling=setInterval(()=>{if(!document.hidden)loadJobs(version).catch(()=>{});},15000);}else if(view==='settings')settings();
 }catch(error){handleError(error);if(version===state.version&&$('content'))$('content').innerHTML=empty('A pause, not a reset.',error.message,'home','Try again');}
}
function updateStatus(){const el=$('connection-status');if(el){el.classList.toggle('online',!!state.stats.workerOnline);el.textContent=state.stats.workerOnline?'Codex connected':'Codex not connected';}}
function handleError(error){if(error.status===401&&state.user){state.active=null;saveActive();login('Your session has expired. Please sign in again.');}else toast(error.message);}
function home(){
 const s=state.stats, accuracy=s.totalAnswers?Math.round(100*s.correctAnswers/s.totalAnswers):null;
 $('content').innerHTML=`<section class="hero"><div><div class="eyebrow">A little more fluent, every day</div><h1>Hello, ${esc(state.user)}.<br>Let’s find your words.</h1><p>Learn a new expression. Revisit a tricky one.<br>Build confidence, one sentence at a time.</p><div class="row"><button class="btn" data-action="start" data-mode="${s.dueCount?'due':'all'}">${s.dueCount?'Review what’s due':'Start a mixed practice'} </button>${state.active?'<button class="btn secondary" data-action="resume">Resume session</button>':''}</div></div><div class="hero-visual" aria-hidden="true"><div class="large-symbol">✳</div><b>Small steps.<br>Lasting words.</b><p>Learn it in context.<br>Recall it with confidence.</p></div></section><div class="stats"><div class="stat"><div class="small">Today’s practice</div><div class="value">${s.todayAnswers}<span>/ 20</span></div><div class="small">questions answered</div></div><div class="stat"><div class="small">Weak items</div><div class="value">${s.weakCount}</div><div class="small">a little more attention</div></div><div class="stat"><div class="small">Review due</div><div class="value">${s.dueCount}</div><div class="small">ready to revisit</div></div></div><div class="section-title row between"><h2>What will you explore?</h2><span class="small muted">B1 → C2</span></div><section class="cards-2"><article class="learning-card peach"><div class="card-icon">Aa</div><h3>Vocabulary</h3><p>One word. Different contexts.<br>Understand how to use it.</p><div class="row between"><span class="small muted">語彙・使い分け</span><button class="btn secondary small" data-action="category" data-kind="vocabulary">Explore</button></div></article><article class="learning-card yellow"><div class="card-icon">a + b</div><h3>Grammar</h3><p>See the pattern. Make it click.<br>Explanations in Japanese.</p><div class="row between"><span class="small muted">文法・例文</span><button class="btn secondary small" data-action="category" data-kind="grammar">Explore</button></div></article></section><section class="review-strip"><div><h3>Your mistakes have a purpose.</h3><p>Wrong answers and guesses become a focused review list.</p></div><button class="btn soft" data-nav="weak">Reinforce weak items</button></section><p class="page-footer">${s.itemCount} starter items · ${s.questionCount} saved questions · ${s.totalAnswers} answers recorded${accuracy!==null?` · ${accuracy}% correct`:''}<br>Progress is saved on the server. Daily totals use Japan time.</p>`;
}
function catalogFrame(view){
 const weak=view==='weak';
 $('content').innerHTML=`<header class="page-heading"><div class="eyebrow">${weak?'Give the tricky things a second chance':'A notebook of useful English'}</div><h1>${weak?'Your weak items.':'Learn it. Use it.'}</h1><p>${weak?'Mistakes and uncertain answers stay here until you recall them across three scheduled reviews.':'Explore vocabulary, meanings, patterns and examples. Then try them in a sentence.'}</p></header>${weak?`<div class="row"><button class="btn" data-action="start" data-mode="weak">Practise weak items</button><button class="btn secondary" data-action="weak-generate">New contexts with Codex</button></div><p class="small muted">First retry: 10 minutes. Successful scheduled reviews: 1 day, 3 days, then 7 days. Early practice does not advance recovery.</p>`:''}<div class="filters"><select id="kind-filter" aria-label="Category">${categories(true,state.kind)}</select><select id="level-filter" aria-label="Level">${levels(true,state.level)}</select><input id="search-filter" type="search" placeholder="Find a word or pattern…" value="${esc(state.search)}" aria-label="Search lessons"></div><div id="catalog-items" class="items"></div><div id="catalog-pagination" class="row between"></div><p class="page-footer">This is a starter library, not the complete B1–C2 inventory. The learning bands are editorial estimates, not official CEFR classifications.</p>`;
}
async function loadItems(version=state.version){
 const request=++itemRequest;
 const r=await api(state.view==='weak'?'weak':'catalog',{kind:state.kind,level:state.level,search:state.search,offset:state.offset});if(version!==state.version||request!==itemRequest||!$('catalog-items'))return;
 $('catalog-items').className=r.items.length?'items':'';
 $('catalog-items').innerHTML=r.items.length?r.items.map(item=>`<article class="item"><div class="row between"><div class="row"><span class="badge">${esc(item.level)}</span><span class="small muted">${item.kind==='grammar'?'Grammar':'Vocabulary'}</span></div><span class="badge ${item.weak?'weak':item.recovery>=3?'stable':''}">${item.weak?'Needs review':item.recovery>=3?'Retained':item.seen?'Learning':'New'}</span></div><h3>${esc(item.label)}</h3><p class="meaning" lang="ja">${esc(item.meaning_ja)}</p><div class="row between"><span class="small muted">${item.weak?`${item.recovery}/3 recovery steps`:`${item.question_count} saved questions`}</span><button class="btn secondary small" data-action="item-practice" data-item="${esc(item.id)}">Practise</button></div>${item.weak?`<p class="small muted">Review: ${formatDate(item.next_due)} JST</p>`:''}<details><summary>Explanation & examples</summary><p class="note" lang="ja">${esc(item.notes_ja)}</p>${(item.examples||[]).map(ex=>`<div class="example"><div class="en">${esc(ex.en)}</div><div class="ja" lang="ja">${esc(ex.ja)}</div></div>`).join('')}<div class="small muted">${item.seen} answers · ${item.correct} correct</div></details></article>`).join(''):empty(state.view==='weak'?'Nothing weak here yet.':'No matching lessons.',state.view==='weak'?'As you practise, missed or uncertain items will appear here automatically.':'Try another filter or search term.','learn',state.view==='weak'?'Find something to learn':'');
 $('catalog-pagination').innerHTML=`${state.offset?'<button class="text-button" data-action="catalog-prev">← Previous</button>':''}${r.items.length===100?'<button class="text-button" data-action="catalog-next">Next →</button>':''}`;
}
async function startPractice(filters={}){
 if(startingPractice)return;startingPractice=true;let r;
 try{r=await api('practice',filters);}finally{startingPractice=false;}
 clearInterval(polling);
 if(!r.questions.length){toast(r.message||'There are no questions for this selection yet.');return;}
 state.active={sessionId:r.sessionId,questions:r.questions,index:0,score:0,weak:0,feedback:null,choice:null,unsure:false,hintUsed:false};saveActive();showPractice();
}
function showPractice(){state.view='practice';state.version++;shell();renderQuestion();window.scrollTo({top:0});}
function renderQuestion(){
 const a=state.active;if(!a)return navigate('home');const q=a.questions[a.index],f=a.feedback;
 $('content').innerHTML=`<section class="quiz"><div class="quiz-top"><button class="text-button" data-nav="home">← Save & leave</button><p>Question ${a.index+1} of ${a.questions.length}</p></div><progress max="${a.questions.length}" value="${a.index+(f?1:0)}" aria-label="Session progress"></progress><article class="question-card"><div class="row between"><span class="eyebrow" style="margin:0">Choose the missing expression</span><span class="badge">${esc(q.level)} · ${esc(q.kind)}</span></div><p class="sentence">${esc(q.sentence).replace('____','<span class="gap">&nbsp;?&nbsp;</span>')}</p><button class="text-button" data-action="hint" ${f?'disabled':''}>${a.hintUsed?'Japanese hint shown':'Need a Japanese hint?'}</button>${a.hintUsed?`<div class="hint" lang="ja">${esc(q.hintJa)}</div>`:''}<div class="options" role="group" aria-label="Answer choices">${q.options.map((o,i)=>`<button class="option ${a.choice===o?'selected':''} ${f&&o===f.answer?'correct':''} ${f&&o===f.choice&&!f.correct?'wrong':''}" data-action="option" data-option="${i}" ${f?'disabled':''} aria-pressed="${a.choice===o}"><span class="letter">${'ABCD'[i]}</span><span>${esc(o)}</span></button>`).join('')}</div>${!f?`<div class="quiz-actions"><label class="check"><input id="unsure" type="checkbox" ${a.unsure||a.hintUsed?'checked':''}> I guessed / I’m not sure</label><button class="btn" id="check-answer" data-action="answer" ${a.choice==null?'disabled':''}>Check answer</button></div>`:''}</article>${f?`<section class="feedback ${!f.correct||f.unsure?'incorrect':''}" aria-live="polite"><h3>${f.correct?(f.unsure?'Correct. Let’s make it confident.':'That’s the expression. ✓'):'A useful one to revisit.'}</h3><div class="answer">${esc(f.answer)}</div><p><strong>${esc(f.label)}</strong> · <span lang="ja">${esc(f.meaningJa)}</span></p><p lang="ja">${esc(f.explanationJa)}</p><p lang="ja">${esc(f.translationJa)}</p><div class="recovery">${f.weak?`Saved in Weak items · ${f.recovery}/3 scheduled recovery steps.`:'Saved to your learning history.'}<br>Next review: ${formatDate(f.nextDue)} JST. ${f.weak?'Early retries do not remove it from your weak list.':''}</div></section><div class="row between"><button class="text-button" data-action="report" data-question="${esc(q.id)}">Report a problem</button><button class="btn" data-action="next">${a.index+1===a.questions.length?'Finish session':'Next sentence'} →</button></div>`:''}<p class="page-footer">${esc(q.source)}. Answers are checked and saved on the server.</p></section>`;
}
async function submitAnswer(){
 const a=state.active;if(!a||a.feedback||a.choice==null)return;
 $('check-answer').disabled=true;document.querySelectorAll('.option').forEach(x=>x.disabled=true);
 try{const f=await api('answer',{sessionId:a.sessionId,questionId:a.questions[a.index].id,choice:a.choice,unsure:!!($('unsure')?.checked||a.hintUsed)});a.feedback=f;a.score+=f.correct?1:0;a.weak+=f.weak?1:0;if(state.active===a){saveActive();if(state.view==='practice')renderQuestion();}}
 catch(error){handleError(error);if(state.active)renderQuestion();}
}
function nextQuestion(){
 const a=state.active;if(!a?.feedback)return;
 a.index++;a.feedback=null;a.choice=null;a.unsure=false;a.hintUsed=false;
 if(a.index>=a.questions.length){const score=a.score,total=a.questions.length,weak=a.weak;state.active=null;saveActive();$('content').innerHTML=`<section class="quiz"><div class="empty"><div class="eyebrow">A little further than before</div><h1>Session complete.</h1><div class="summary-score">${score}<span class="muted"> / ${total}</span></div><p>Every answer is saved.${weak?` ${weak} answers involved items that still need reinforcement.`:' Your next reviews are scheduled.'}</p><div class="row" style="justify-content:center"><button class="btn" data-nav="weak">See weak items</button><button class="btn secondary" data-nav="home">Back to your notebook</button></div></div></section>`;}else{saveActive();renderQuestion();window.scrollTo({top:0,behavior:'smooth'});}
}
function historyFrame(){
 $('content').innerHTML=`<header class="page-heading"><div class="eyebrow">Your progress, sentence by sentence</div><h1>A record of getting better.</h1><p>Your answers, corrections and explanations, kept together.</p></header><div class="row between"><div class="chips"><button class="chip ${!state.mistakes?'active':''}" data-action="history-all">All answers</button><button class="chip ${state.mistakes?'active':''}" data-action="history-mistakes">Mistakes & guesses</button></div><button class="text-button" data-action="export">Export history</button></div><div class="history-list" id="history-list"></div><div class="row between" id="history-pagination"></div>`;
}
async function loadHistory(version=state.version){
 const request=++historyRequest;
 const r=await api('history',{offset:state.historyOffset,mistakes:state.mistakes});if(version!==state.version||request!==historyRequest||!$('history-list'))return;
 $('history-list').innerHTML=r.attempts.length?r.attempts.map(a=>{const f=a.feedback;return `<article class="history-item"><div class="row between"><div class="row"><span class="badge ${!f.correct||f.unsure?'weak':'stable'}">${f.correct?(f.unsure?'Guessed':'Correct'):'Revisit'}</span><strong class="small">${esc(f.label)}</strong></div><span class="date">${formatDate(a.created_at)} JST</span></div><p class="sentence">${esc(f.sentence).replace('____',`<strong>${esc(f.answer)}</strong>`)}</p>${!f.correct?`<p class="small muted">Your answer: ${esc(f.choice)}</p>`:''}<details><summary>Why this works</summary><p lang="ja">${esc(f.explanationJa)}</p><p lang="ja">${esc(f.translationJa)}</p><button class="btn secondary small" data-action="item-practice" data-item="${esc(f.itemId)}">Try another context</button></details></article>`;}).join(''):empty('Your story starts here.',state.mistakes?'No mistakes or guesses in this selection.':'Once you answer a question, you’ll find it here.');
 $('history-pagination').innerHTML=`${state.historyOffset?'<button class="text-button" data-action="history-prev">← Newer answers</button>':''}${r.attempts.length===30?'<button class="text-button" data-action="history-next">Older answers →</button>':''}`;
}
function generator(){
 const g=state.generation;
 $('content').innerHTML=`<header class="page-heading"><div class="eyebrow">Same learning goal. A fresh context.</div><h1>Make room for new sentences.</h1><p>Ask the private Codex worker for a new practice batch. Saved questions can be practised again without another generation request.</p></header><div class="generate-grid"><section class="panel"><h2>Create a practice batch</h2><div id="generator-notice" class="notice"><strong>${state.stats.workerOnline?'Your Codex worker is connected.':'Codex is not connected yet.'}</strong>${state.stats.workerOnline?'Requests use the connected Codex account.':'Requests can wait in the queue, but no new questions are generated until the owner starts and connects the Codex worker.'}</div><form id="generate-form"><div class="form-grid"><label class="field">Category<select name="kind">${categories(false,g.kind)}</select></label><label class="field">Practice level<select name="level">${levels(false,g.level)}</select></label><label class="field">Questions<select name="count">${[5,10,20].map(n=>`<option value="${n}" ${n===Number(g.count)?'selected':''}>${n} questions</option>`).join('')}</select></label><label class="field">Context<select name="topic">${['mixed','daily life','work','travel'].map(t=>`<option ${t===g.topic?'selected':''}>${esc(t)}</option>`).join('')}</select></label></div><label class="check"><input type="checkbox" name="weakOnly" ${g.weakOnly?'checked':''}> Focus only on weak items at this level</label><p class="small muted">6 batches per 24 hours. One active request at a time. Only lesson targets, not your login or personal history, go to Codex.</p><button type="submit" class="btn">${state.stats.workerOnline?'Generate new questions':'Queue a request'} ✳</button></form></section><section class="panel"><div class="row between"><h2>Your batches</h2><button class="text-button" data-action="refresh-jobs">Refresh</button></div><div id="jobs-list"><p class="small muted">Loading your batches…</p></div></section></div><p class="page-footer">Generated questions are automatically checked, not human-reviewed. Report an incorrect question during practice to remove it from future sessions.</p>`;
}
async function loadJobs(version=state.version){
 const [r,s]=await Promise.all([api('jobs'),api('dashboard')]);if(version!==state.version||!$('jobs-list'))return;
 state.stats=s;updateStatus();
 $('jobs-list').innerHTML=r.jobs.length?r.jobs.map(j=>`<article class="job"><div class="row between"><h3>${esc(j.level)} ${esc(j.kind)} · ${j.count} questions</h3><span class="state ${esc(j.state)}">${esc(j.state==='queued'&&!s.workerOnline?'waiting for Codex':j.state)}</span></div><p>${formatDate(j.created_at)} JST${j.state==='completed'?` · ${j.question_count} saved`:''}</p>${j.error?`<p>${esc(({cancelled:'Cancelled by you.',quota:'Codex usage limit reached. Saved practice still works.',auth_required:'The owner needs to sign in to Codex.',validation:'The generated batch did not pass the checks.',timeout:'Generation took too long.',worker_timeout:'The worker stopped responding.'})[j.error]||'Generation could not finish. Please try again.')}</p>`:''}${j.state==='completed'?`<button class="btn secondary small" data-action="batch-practice" data-job="${esc(j.id)}">Practise this batch</button>`:j.state==='queued'?`<button class="text-button" data-action="cancel-job" data-job="${esc(j.id)}">Cancel request</button>`:''}</article>`).join(''):'<p class="small muted">Your first batch will appear here. The starter questions are already available in Learn.</p>';
 const notice=$('generator-notice');if(notice)notice.innerHTML=s.workerOnline?'<strong>Your Codex worker is connected.</strong>Requests use the connected Codex account.':'<strong>Codex is not connected yet.</strong>Requests wait here until the owner starts and connects the Codex worker. Saved lessons are still available.';
}
function settings(){
 $('content').innerHTML=`<section class="settings"><header class="page-heading"><div class="eyebrow">Your space, your control</div><h1>Settings & your data.</h1></header><section class="panel"><h3>Signed in as ${esc(state.user)}</h3><p class="small muted">Your history and weak-item progress are saved on the server, not only on this device. Export keeps a readable copy of your study records.</p><div class="row"><button class="btn secondary" data-action="export">Export my progress</button><button class="text-button" data-action="logout">Sign out</button></div></section><section class="panel"><h3>Connect your Codex</h3><p class="small">On the computer where you use Codex, open Eego’s repo folder and run the connection command in the README. Your saved Codex login generates new questions while that worker is running.</p><a class="text-button" href="https://github.com/Logan17de/My-works/tree/main/eego-web-app#connect-your-codex" target="_blank" rel="noopener noreferrer">Open connection instructions</a></section><section class="panel"><h3>Change your password</h3><p class="small muted">A longer password is safer than a four-digit PIN. This will sign out other sessions.</p><form id="password-form"><label class="field">Current password<input type="password" name="currentPassword" required autocomplete="current-password" maxlength="128"></label><label class="field">New password<input type="password" name="newPassword" required minlength="10" maxlength="128" autocomplete="new-password"></label><button class="btn" type="submit">Update password</button></form></section><section class="panel"><h3>How reinforcement works</h3><p class="small">A wrong answer or an uncertain guess puts the item into your weak list. After 10 minutes, answer correctly in a different sentence. The next scheduled reviews are 1 day and 3 days later. Three successful scheduled review steps move it out of the weak list, with another review after 7 days.</p><p class="small muted">Immediate retries still appear in history, but they do not count as spaced recovery. Levels are approximate learning bands; progress is not a CEFR certification.</p></section><p class="page-footer">Eego 1.0.0 · Private vocabulary & grammar practice.<br>Exports contain your learning records. Keep them private.</p></section>`;
}
async function exportData(){const data=await api('export');const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`eego-study-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);toast('Your study export is ready.');}
document.addEventListener('click',async event=>{
 const el=event.target.closest('button[data-nav],button[data-action]');if(!el||el.disabled)return;
 if(el.dataset.nav){if(el.dataset.nav!==state.view){state.offset=0;state.search='';}return navigate(el.dataset.nav);}
 const action=el.dataset.action;
 try{
  if(action==='toggle-password'){const p=$('login-password');p.type=p.type==='password'?'text':'password';el.textContent=p.type==='password'?'Show':'Hide';el.setAttribute('aria-label',`${el.textContent} password`);}
  else if(action==='category'){state.kind=el.dataset.kind;state.level='all';state.offset=0;state.search='';await navigate('learn');}
  else if(action==='start'){await startPractice({mode:el.dataset.mode||'all',kind:state.view==='weak'?state.kind:'all',level:state.view==='weak'?state.level:'all'});}
  else if(action==='item-practice')await startPractice({itemId:el.dataset.item});
  else if(action==='batch-practice')await startPractice({jobId:el.dataset.job});
  else if(action==='resume'&&state.active)showPractice();
  else if(action==='option'&&!state.active.feedback){state.active.choice=state.active.questions[state.active.index].options[Number(el.dataset.option)];state.active.unsure=!!$('unsure')?.checked;saveActive();renderQuestion();}
  else if(action==='hint'&&!state.active.feedback){state.active.hintUsed=true;state.active.unsure=true;saveActive();renderQuestion();}
  else if(action==='answer')await submitAnswer();
  else if(action==='next')nextQuestion();
  else if(action==='report'){await api('report',{questionId:el.dataset.question});el.disabled=true;el.textContent='Reported';toast('Reported. This question will not appear in future practice.');}
  else if(action==='weak-generate'){state.generation.weakOnly=true;state.generation.kind=state.kind==='all'?'vocabulary':state.kind;state.generation.level=state.level==='all'?'B1':state.level;await navigate('generate');}
  else if(action==='refresh-jobs')await loadJobs();
  else if(action==='cancel-job'){await api('cancel_job',{jobId:el.dataset.job});await loadJobs();}
  else if(action==='history-all'||action==='history-mistakes'){state.mistakes=action==='history-mistakes';state.historyOffset=0;historyFrame();await loadHistory();}
  else if(action==='history-prev'||action==='history-next'){state.historyOffset=Math.max(0,state.historyOffset+(action.endsWith('next')?30:-30));await loadHistory();window.scrollTo({top:0});}
  else if(action==='catalog-prev'||action==='catalog-next'){state.offset=Math.max(0,state.offset+(action.endsWith('next')?100:-100));await loadItems();window.scrollTo({top:0});}
  else if(action==='export')await exportData();
  else if(action==='logout'){await api('logout');state.active=null;saveActive();login();}
 }catch(error){handleError(error);}
});
document.addEventListener('change',event=>{
 if(event.target.id==='kind-filter'){state.kind=event.target.value;state.offset=0;loadItems().catch(handleError);}
 if(event.target.id==='level-filter'){state.level=event.target.value;state.offset=0;loadItems().catch(handleError);}
 if(event.target.id==='unsure'&&state.active){state.active.unsure=event.target.checked;saveActive();}
});
document.addEventListener('input',event=>{if(event.target.id==='search-filter'){state.search=event.target.value;state.offset=0;clearTimeout(searchTimer);searchTimer=setTimeout(()=>loadItems().catch(handleError),250);}});
document.addEventListener('submit',async event=>{
 const form=event.target;if(!['login-form','generate-form','password-form'].includes(form.id))return;
 event.preventDefault();const button=form.querySelector('button[type="submit"]');const original=button.textContent;button.disabled=true;button.textContent='One moment…';const data=Object.fromEntries(new FormData(form));
 try{
  if(form.id==='login-form'){const r=await api('login',data);state.user=r.username;restoreActive();await navigate('home');}
  else if(form.id==='generate-form'){data.count=Number(data.count);data.weakOnly=!!data.weakOnly;state.generation=data;const r=await api('generate',data);toast(r.workerOnline?'Your batch is queued for Codex.':'Request saved. Waiting for the owner’s Codex worker.');await loadJobs();}
  else{await api('password',data);form.reset();toast('Password updated. Other sessions have been signed out.');}
 }catch(error){if(form.id==='login-form'){$('login-error').textContent=error.message;$('login-error').classList.remove('hidden');}else if(form.id==='password-form')toast(error.message);else handleError(error);}
 finally{if(button.isConnected){button.disabled=false;button.textContent=original;}}
});
(async()=>{try{const s=await api('me');state.user=s.username;state.stats=s;restoreActive();await navigate('home');}catch(error){login(error.status===401?'':error.message);}})();

// Optional browser agent controls use the same authenticated application state.
if(document.modelContext?.registerTool){
 for(const tool of [
 {name:'eego_get_study_status',description:'Read your signed-in Eego progress and Codex connection status.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async()=>{if(!state.user)throw new Error('Sign in to Eego first.');return api('dashboard');}},
 {name:'eego_open_lessons',description:'Open the vocabulary or grammar library at a selected level.',inputSchema:{type:'object',properties:{kind:{enum:['all','vocabulary','grammar']},level:{enum:['all','B1','B2','C1','C2']}},required:['kind','level'],additionalProperties:false},execute:async(input)=>{if(!state.user)throw new Error('Sign in to Eego first.');if(!['all','vocabulary','grammar'].includes(input?.kind)||!['all','B1','B2','C1','C2'].includes(input?.level))throw new Error('Invalid category or level.');state.kind=input.kind;state.level=input.level;state.offset=0;state.search='';await navigate('learn');return{view:state.view,kind:state.kind,level:state.level};}}
 ]){try{Promise.resolve(document.modelContext.registerTool(tool)).catch(()=>{});}catch{}}
}
