-- Eego is isolated from AIKO and all existing application tables.
create schema if not exists eego;
revoke all on schema eego from public, anon, authenticated;
create extension if not exists pgcrypto with schema extensions;
create table eego.users (id uuid primary key default gen_random_uuid(), username text not null unique, password_hash text not null, created_at timestamptz not null default now());
create table eego.sessions (token_hash text primary key, user_id uuid not null references eego.users on delete cascade, expires_at timestamptz not null, created_at timestamptz not null default now());
create index on eego.sessions(user_id);
create table eego.throttle (key text primary key, failures int not null default 0, reset_at timestamptz not null);
create table eego.items (id text primary key, kind text not null check(kind in ('vocabulary','grammar')), level text not null check(level in ('B1','B2','C1','C2')), label text not null, meaning_ja text not null default '', notes_ja text not null default '', source text not null default 'Original Eego starter; level is an editorial estimate', examples jsonb not null default '[]');
create table eego.workers (id text primary key, user_id uuid references eego.users on delete cascade, token_hash text not null unique, enabled boolean not null default true, ready boolean not null default false, last_seen timestamptz);
create table eego.jobs (id uuid primary key default gen_random_uuid(), user_id uuid not null references eego.users on delete cascade, kind text not null, level text not null, count int not null check(count between 1 and 20), targets text[] not null, topic text not null, state text not null default 'queued' check(state in ('queued','running','completed','failed')), created_at timestamptz not null default now(), finished_at timestamptz, lease_token text, lease_until timestamptz, worker_id text references eego.workers, tries int not null default 0, error text, question_count int not null default 0);
create index on eego.jobs(user_id,created_at desc);
create index on eego.jobs(state,created_at);
create index on eego.jobs(worker_id);
create table eego.questions (id uuid primary key default gen_random_uuid(), item_id text not null references eego.items, sentence text not null, options jsonb not null check(jsonb_array_length(options)=4), answer text not null, hint_ja text not null, explanation_ja text not null, translation_ja text not null, source text not null default 'Original Eego starter', job_id uuid references eego.jobs, fingerprint text not null unique, reported boolean not null default false, created_at timestamptz not null default now());
create index on eego.questions(item_id);
create index on eego.questions(job_id);
create table eego.practice (id uuid primary key default gen_random_uuid(), user_id uuid not null references eego.users on delete cascade, question_ids uuid[] not null, created_at timestamptz not null default now());
create index on eego.practice(user_id,created_at desc);
create table eego.mastery (user_id uuid not null references eego.users on delete cascade, item_id text not null references eego.items, seen int not null default 0, correct int not null default 0, lapses int not null default 0, weak boolean not null default false, recovery int not null default 0, last_question uuid, next_due timestamptz not null default now(), updated_at timestamptz not null default now(), primary key(user_id,item_id));
create index on eego.mastery(item_id);
create table eego.attempts (id uuid primary key default gen_random_uuid(), user_id uuid not null references eego.users on delete cascade, session_id uuid not null references eego.practice on delete cascade, question_id uuid not null references eego.questions, item_id text not null references eego.items, correct boolean not null, unsure boolean not null default false, feedback jsonb not null, created_at timestamptz not null default now(), unique(session_id,question_id));
create index on eego.attempts(user_id,created_at desc);
create index on eego.attempts(question_id);
create index on eego.attempts(item_id);
create table eego.reports (id uuid primary key default gen_random_uuid(), user_id uuid not null references eego.users on delete cascade, question_id uuid not null references eego.questions, created_at timestamptz not null default now(), unique(user_id,question_id));
create index on eego.reports(question_id);
do $$ declare t record; begin for t in select tablename from pg_tables where schemaname='eego' loop execute format('alter table eego.%I enable row level security',t.tablename); end loop; end $$;
revoke all on all tables in schema eego from public,anon,authenticated;
